AssetsVersion: 3c3d6b1ec6eb177ae599ebcdc11cce0a81ceca2b
AssetsBaseURL: https://bettr-casino-assets.s3.us-west-2.amazonaws.com
OutcomesVersion: 3c3d6b1ec6eb177ae599ebcdc11cce0a81ceca2b
OutcomesBaseURL: https://qyikpc6uniqdv45wk65iy3a2c40qbhtk.lambda-url.us-west-2.on.aws/
MainBundleName: main
MainBundleVariant: v0_1_0
