AssetsVersion: 1b53e2e08a9e5828e300a4c0b99166d231a50a6d
AssetsBaseURL: https://bettr-casino-assets.s3.us-west-2.amazonaws.com
OutcomesVersion: 1b53e2e08a9e5828e300a4c0b99166d231a50a6d
OutcomesBaseURL: https://qyikpc6uniqdv45wk65iy3a2c40qbhtk.lambda-url.us-west-2.on.aws/
MainBundleName: main
MainBundleVariant: v0_1_0
